
# Create a list and a matrix with numpy 

In [1]:
import numpy as np

In [2]:
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


In [3]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40,45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
vector_shape = vector.shape
matrix_shape = matrix.shape

In [5]:
print(vector_shape)

(3,)


In [6]:
matrix_shape

(3, 3)

# World alcohol dataset


In [7]:
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)

In [8]:
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [9]:
world_alcohol_dtype = world_alcohol.dtype
world_alcohol_dtype

dtype('<U75')

In [10]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [11]:
ivoire_country = world_alcohol[2,4]
second_country = world_alcohol[1,2]

print(ivoire_country)
print(second_country)

1.62
Uruguay


In [12]:
countries = world_alcohol[:,2]
alcohol_consumption = world_alcohol[:, 4]

In [13]:
print(countries)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [14]:
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


In [15]:
first_two_columns = world_alcohol[:, :2]
print(first_two_columns)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [16]:
first_ten_years = world_alcohol[:10,0]
print(first_ten_years)

['1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986' '1984']


In [17]:
first_ten_rows = world_alcohol[:10,:]
print(first_ten_rows)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [18]:
first_twenty_regions = world_alcohol[:20, 1:3]
print(first_twenty_regions)

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]



# Comparaison with numpy 

In [19]:
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [20]:
country_canada = world_alcohol[:,2]
print(country_canada)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [21]:
for i in range(country_canada.shape[0]):
    if country_canada[i] == "Canada":
        print(f"Canada at index : {i}")

Canada at index : 146
Canada at index : 274
Canada at index : 352
Canada at index : 547
Canada at index : 571
Canada at index : 1152
Canada at index : 1269
Canada at index : 1625
Canada at index : 1707
Canada at index : 2059
Canada at index : 2090
Canada at index : 2308
Canada at index : 2540
Canada at index : 3068
Canada at index : 3069
Canada at index : 3089
Canada at index : 3139
Canada at index : 3153
Canada at index : 3211
Canada at index : 3237


In [22]:
world_alcohol[571,2]

'Canada'

In [23]:
year_1984 = world_alcohol[:,0]
print(year_1984)

['1986' '1986' '1985' ... '1986' '1987' '1986']


In [24]:
year_1984 == "1984"

array([False, False, False, ..., False, False, False])

In [25]:
for i in range(year_1984.shape[0]):
    if year_1984[i] == "1984":
        print(f"1984 at index : {i}")
    

1984 at index : 9
1984 at index : 13
1984 at index : 16
1984 at index : 18
1984 at index : 19
1984 at index : 22
1984 at index : 23
1984 at index : 25
1984 at index : 27
1984 at index : 42
1984 at index : 43
1984 at index : 53
1984 at index : 54
1984 at index : 58
1984 at index : 61
1984 at index : 95
1984 at index : 97
1984 at index : 98
1984 at index : 109
1984 at index : 117
1984 at index : 127
1984 at index : 128
1984 at index : 132
1984 at index : 135
1984 at index : 146
1984 at index : 160
1984 at index : 163
1984 at index : 165
1984 at index : 172
1984 at index : 174
1984 at index : 178
1984 at index : 181
1984 at index : 205
1984 at index : 214
1984 at index : 222
1984 at index : 240
1984 at index : 245
1984 at index : 253
1984 at index : 260
1984 at index : 262
1984 at index : 267
1984 at index : 269
1984 at index : 276
1984 at index : 277
1984 at index : 283
1984 at index : 296
1984 at index : 300
1984 at index : 302
1984 at index : 305
1984 at index : 307
1984 at index : 308

1984 at index : 2038
1984 at index : 2050
1984 at index : 2065
1984 at index : 2076
1984 at index : 2079
1984 at index : 2094
1984 at index : 2103
1984 at index : 2107
1984 at index : 2122
1984 at index : 2125
1984 at index : 2128
1984 at index : 2141
1984 at index : 2145
1984 at index : 2146
1984 at index : 2150
1984 at index : 2159
1984 at index : 2166
1984 at index : 2170
1984 at index : 2173
1984 at index : 2177
1984 at index : 2183
1984 at index : 2186
1984 at index : 2194
1984 at index : 2195
1984 at index : 2204
1984 at index : 2221
1984 at index : 2236
1984 at index : 2243
1984 at index : 2244
1984 at index : 2249
1984 at index : 2253
1984 at index : 2254
1984 at index : 2270
1984 at index : 2284
1984 at index : 2286
1984 at index : 2287
1984 at index : 2292
1984 at index : 2293
1984 at index : 2308
1984 at index : 2311
1984 at index : 2313
1984 at index : 2327
1984 at index : 2329
1984 at index : 2330
1984 at index : 2341
1984 at index : 2344
1984 at index : 2345
1984 at index

In [26]:
contry_is_algeria = world_alcohol[:,2] == "Algeria"
contry_is_algeria

array([False, False, False, ..., False, False, False])

In [27]:
contry_algeria = world_alcohol[contry_is_algeria]
print(contry_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [28]:
year_is_1984 = world_alcohol[:,0] == "1984"
year_is_1984

array([False, False, False, ..., False, False, False])

In [29]:
year_1984 = world_alcohol[year_is_1984]
print(year_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [30]:
is_algeria_and_1986 = (world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Algeria")
print(is_algeria_and_1986)

[False False False ... False False False]


In [31]:
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]
rows_with_algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], dtype='<U75')

In [32]:
world_alcohol_2 = world_alcohol
print(world_alcohol_2)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [33]:
world_alcohol_2[world_alcohol_2[:,0] == "1986", 0] = "2018"

In [34]:
world_alcohol_2

array([['2018', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [35]:
world_alcohol[world_alcohol_2[:,3] == "Wine", 3] = "Beer"

In [36]:
world_alcohol

array([['2018', 'Western Pacific', 'Viet Nam', 'Beer', '0'],
       ['2018', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Beer', '1.62'],
       ...,
       ['2018', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2018', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [38]:
is_value_empty = world_alcohol[:, 4] == ""
is_value_empty

array([False, False, False, ..., False, False, False])

In [40]:
world_alcohol[is_value_empty] 

array([['1985', 'Africa', 'Comoros', 'Other', ''],
       ['2018', 'Europe', 'Italy', 'Other', ''],
       ['1985', 'Europe', 'Lithuania', 'Other', ''],
       ...,
       ['1984', 'Europe', 'Czech Republic', 'Other', ''],
       ['1987', 'Americas', 'Canada', 'Other', ''],
       ['2018', 'Europe', 'Poland', 'Other', '']], dtype='<U75')

In [42]:
world_alcohol[is_value_empty, 4] = "0"
world_alcohol[is_value_empty]

array([['1985', 'Africa', 'Comoros', 'Other', '0'],
       ['2018', 'Europe', 'Italy', 'Other', '0'],
       ['1985', 'Europe', 'Lithuania', 'Other', '0'],
       ...,
       ['1984', 'Europe', 'Czech Republic', 'Other', '0'],
       ['1987', 'Americas', 'Canada', 'Other', '0'],
       ['2018', 'Europe', 'Poland', 'Other', '0']], dtype='<U75')

In [46]:
alcohol_consomption = world_alcohol[:,4]

In [63]:
alcohol_consomption = alcohol_consomption.astype(float)

In [66]:
total_alcohol = alcohol_consomption.sum()
average_alcohol = alcohol_consomption.mean()

print(f"""
Total alcohol : {total_alcohol}
Average alcohol : {average_alcohol} 

""")



Total alcohol : 3908.96
Average alcohol : 1.2001719373656738 




In [57]:
vec = np.array([2.3, 4, 6])
vec.sum()

12.3

Alcohol consomption for canada in 1986

In [68]:
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)

In [70]:
canada_1986 = world_alcohol[(world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Canada")]
canada_1986

array([['1986', 'Americas', 'Canada', 'Other', ''],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [75]:
canada_1986[canada_1986[:,4] == "", 4] =  "0"

In [76]:
canada_1986

array([['1986', 'Americas', 'Canada', 'Other', '0'],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [77]:
canada_alcohol = canada_1986[:, 4].astype(float)
canada_alcohol

array([0.  , 3.11, 4.87, 1.33])

In [78]:
total_canada_drinking = canada_alcohol.sum()

In [79]:
total_canada_drinking

9.31

Alcohol consomption for each contry in 1989


In [80]:
year = world_alcohol[world_alcohol[:,0] == "1989"]
year

array([['1989', 'Americas', 'Guatemala', 'Beer', '0.62'],
       ['1989', 'Africa', 'Seychelles', 'Beer', '2.23'],
       ['1989', 'Americas', 'Costa Rica', 'Spirits', '4.51'],
       ...,
       ['1989', 'Eastern Mediterranean', 'Morocco', 'Spirits', '0.07'],
       ['1989', 'Europe', 'Poland', 'Beer', '2.03'],
       ['1989', 'Europe', 'Turkey', 'Other', '0']], dtype='<U75')

In [89]:
column_contry = year[:,2]
contries = []

for i in range(column_contry.shape[0]):
    if not column_contry[i] in contries:
        contries.append(column_contry[i])
        
print(f"{len(contries)} : {contries}")

164 : ['Guatemala', 'Seychelles', 'Costa Rica', 'Mauritius', 'Zimbabwe', 'Suriname', 'Croatia', 'Syrian Arab Republic', 'Bolivia (Plurinational State of)', 'Somalia', 'Namibia', 'Uganda', 'Afghanistan', 'Jamaica', 'Finland', 'Iraq', 'Malawi', 'Bulgaria', 'Nicaragua', 'Central African Republic', 'Burundi', 'Sweden', 'Greece', 'Kyrgyzstan', 'Belgium', 'Angola', 'Burkina Faso', 'Czech Republic', 'United Arab Emirates', 'Peru', 'Trinidad and Tobago', 'Guyana', 'Bahrain', 'Benin', 'Liberia', 'Viet Nam', 'Belarus', 'Swaziland', 'France', 'United States of America', 'Cabo Verde', 'Saudi Arabia', 'Poland', 'Senegal', 'Slovenia', 'Hungary', 'Iran (Islamic Republic of)', 'Lesotho', 'Gabon', 'Comoros', 'Italy', 'Denmark', 'Canada', 'Zambia', 'Botswana', 'Kuwait', 'Russian Federation', 'New Zealand', 'Uruguay', 'Fiji', 'Israel', "Cte d'Ivoire", 'Spain', 'South Africa', 'Morocco', 'Venezuela (Bolivarian Republic of)', 'Egypt', 'Ethiopia', 'Bhutan', 'Chile', 'Cambodia', 'Mali', 'Nepal', 'Kiribati', 

In [102]:
totals = {}

for contry in range(len(contries)):
    contry_consomption = year[year[:,2] == contries[contry]]
    
    alcohol_contry_consomption = contry_consomption[:,4]
    alcohol_contry_consomption[alcohol_contry_consomption == ""] = "0"
    alcohol_contry_consomption = alcohol_contry_consomption.astype(float)
    
    total_contry_consomption = alcohol_contry_consomption.sum()
    
    totals[contries[contry]] = total_contry_consomption
    
    
print(totals)
    

{'Guatemala': 2.47, 'Seychelles': 3.3000000000000003, 'Costa Rica': 5.3999999999999995, 'Mauritius': 3.54, 'Zimbabwe': 4.92, 'Suriname': 3.67, 'Croatia': 10.92, 'Syrian Arab Republic': 0.54, 'Bolivia (Plurinational State of)': 3.05, 'Somalia': 0.0, 'Namibia': 0.24, 'Uganda': 7.8, 'Afghanistan': 0.0, 'Jamaica': 3.03, 'Finland': 9.419999999999998, 'Iraq': 0.75, 'Malawi': 1.02, 'Bulgaria': 11.43, 'Nicaragua': 2.5, 'Central African Republic': 2.5199999999999996, 'Burundi': 8.159999999999998, 'Sweden': 7.47, 'Greece': 10.15, 'Kyrgyzstan': 4.279999999999999, 'Belgium': 11.61, 'Angola': 2.28, 'Burkina Faso': 3.99, 'Czech Republic': 13.009999999999998, 'United Arab Emirates': 4.43, 'Peru': 4.99, 'Trinidad and Tobago': 4.68, 'Guyana': 9.940000000000001, 'Bahrain': 4.89, 'Benin': 1.3800000000000001, 'Liberia': 5.61, 'Viet Nam': 0.16, 'Belarus': 7.9799999999999995, 'Swaziland': 6.68, 'France': 16.05, 'United States of America': 9.16, 'Cabo Verde': 2.79, 'Saudi Arabia': 0.15, 'Poland': 9.33, 'Sene

In [117]:
highest_value = 0
highest_contry = ""
for k,v in totals.items():
    if v > highest_value:
        highest_value = v
        highest_contry = k
        
print(f"{highest_contry} : {highest_value}")

Hungary : 16.29


In [116]:
def check_value(searched_country):
    for k,v in totals.items():
        if k == searched_country:
            print(f"{k} : {v}")
            
check_value("Costa Rica")

Costa Rica : 5.3999999999999995
